Cargo.lock
Cargo.toml
src/lib.rs
src/testing/consensus.rs
src/testing/mocks.rs
src/update.rs

Necessary for the cdn-server -> web-server transition in `espresso-sequencer`

Point to `paper_benchmarking` HotShot branch

---

flake.nix

This should fix the coverage workflow

Add RUSTFLAGS to perfShell

---

README.md
src/availability/query_data.rs
src/testing/mocks.rs

fix: QueryableBlock return an owned Transaction

---

.github/workflows/lint.yml
Cargo.toml
examples/simple-server.rs
src/data_source.rs
src/data_source/extension.rs
src/data_source/fs.rs
src/data_source/metrics.rs
src/data_source/sql.rs
src/status/data_source.rs
src/testing/consensus.rs
src/testing/mocks.rs

Minimal metrics-only data source for status API

---

api/availability.toml
migrations/V10__init_schema.sql
src/availability.rs
src/data_source.rs
src/data_source/sql.rs

Followups now that we have proper support for block headers

---

Cargo.lock
Cargo.toml
src/data_source/sql.rs

* Support TLS (closes https://github.com/EspressoSystems/hotshot-query-service/issues/322)
* Parse from URI (closes https://github.com/EspressoSystems/hotshot-query-service/issues/323)

Improve SQL configurability

---

Cargo.lock
Cargo.toml

Update HotShot to release 0.5.5.

Update HotShot to 0.5.5

---

Cargo.lock
Cargo.toml
migrations/V10__init_schema.sql
src/availability.rs
src/availability/data_source.rs
src/availability/query_data.rs
src/data_source.rs
src/data_source/extension.rs
src/data_source/fs.rs
src/data_source/sql.rs
src/lib.rs
src/testing/mocks.rs

This required a HotShot update, which in turn resulted in a number of minor changes related to proposer IDs/signature keys.
Closes #328

Add payload metadata parameter to QueryablePayload methods

---

Cargo.lock
Cargo.toml
examples/simple-server.rs
src/lib.rs
src/node.rs
src/testing/consensus.rs
src/testing/mocks.rs

chore: update hotshot to 0.5.7

---

Cargo.lock
Cargo.toml
src/data_source/fetching.rs
src/fetching.rs
src/fetching/provider.rs
src/fetching/provider/any.rs
src/fetching/provider/query_service.rs
src/fetching/provider/testing.rs

See commit messages for details

Follow-up for async fetching, changes needed for sequencer integration

---

Cargo.lock
Cargo.toml

need for light client prover service

upgrade to hotshot 0.5.10

---

src/data_source/storage/sql.rs

The first barrier to being able to remotely target a Docker
container is the inability to target a host other than
localhost.
This commit adds host to the TmpDb struct, and utilizes it
to populate the generated configuration. This will allow for
the client that consumes the Config to be able to target
a different host other than "localhost".
Add derived hostname for docker host
The second barrier is to actually populate the now
configurable Hostname.  We require the ability to specify
the hostname of the remote docker instance.
In order to fulfill this requirement I've opted to specify
the remote docker hostname via an environment variable
named "DOCKER_HOSTNAME".  We don't want to use
"DOCKER_HOST" as it's already in use by `docker` itself
for specifying a different target.  In this case …

Add host to TmpDb struct

---

Cargo.lock
Cargo.toml
examples/simple-server.rs
src/availability.rs
src/availability/query_data.rs
src/data_source.rs
src/data_source/fetching.rs
src/data_source/metrics.rs
src/lib.rs
src/status.rs
src/testing/consensus.rs
src/testing/mocks.rs

updates tag version and does a `cargo update`

Update HotShot to 0.5.11

---

src/data_source/fetching.rs
src/data_source/storage/sql.rs

See commit messages for details

Quieter logging for benign events

---

api/availability.toml
src/availability.rs

addresses https://github.com/EspressoSystems/hotshot-query-service/issues/409

add range endpoints for leaf, block, payload and header

---

Cargo.lock
Cargo.toml

chore: upgrade hotshot and jellyfish

---

src/data_source/extension.rs
src/data_source/storage/sql.rs

Merklized State::Commit already implements the Send bound and this is not needed

remove Send bound for state commitment

---

Cargo.lock
Cargo.toml
examples/simple-server.rs
src/availability/query_data.rs
src/data_source.rs
src/data_source/storage/sql.rs
src/data_source/update.rs
src/fetching/provider/query_service.rs
src/status.rs

Update hotshot to tag 0.5.42

---

Cargo.lock
Cargo.toml
examples/simple-server.rs
src/testing/consensus.rs

Uses `true` for `is_da` in `MockNetwork` and in the simple server example

Update HotShot, make DA conditional

---

api/state.toml
src/merklized_state.rs

This is really useful to have for debugging

Expose synced merklized state height

---

Cargo.lock
Cargo.toml

Bump HotShot to 0.5.48

---

Cargo.lock
Cargo.toml
src/data_source/extension.rs
src/data_source/fetching.rs
src/data_source/storage/sql.rs
src/merklized_state/data_source.rs

Closes  https://github.com/EspressoSystems/hotshot-query-service/issues/569
Individual queries combined with a UNION operation are significantly faster and less expensive to execute compared to queries using the LTREE operation. 
- Removes LTREE 
- Batch insert children hashes and node hashes in one query
src/data_source/storage/sql.rs

Optimize merkle path query

---

Cargo.lock
Cargo.toml
src/availability/query_data.rs
src/data_source.rs
src/data_source/extension.rs
src/data_source/fetching.rs
src/data_source/sql.rs
src/data_source/storage/sql.rs
src/data_source/update.rs
src/fetching/provider/query_service.rs
src/merklized_state/data_source.rs
src/testing/mocks.rs

No issue related.
Update Jellyfish/HotShot deps w.r.t the recent Jellyfish crates restructure.

chore: update Jellyfish/HotShot deps

---

src/data_source/extension.rs
src/data_source/fetching.rs
src/data_source/storage.rs
src/data_source/storage/sql.rs
src/explorer.rs
src/explorer/query_data.rs
src/explorer/traits.rs
src/testing/mocks.rs

Closes #579 
Removes the `namespace_ids_for_offset` method from the `ExplorerHeader` trait in favor of a `namespace_id` method on a new trait `ExplorerTransaction`.
Add any consideration for representing the `NamespaceId` on the `MockTransaction` struct.
src/explorer/traits.rs
This is where the new trait is defined, and the previous method is removed.
src/testing/mocks.rs
This is where the traits are implemented for testing

Remove `namespace_ids_for_offset` from `ExplorerHeader`

---

Cargo.lock
Cargo.toml
api/availability.toml
src/availability.rs
src/availability/data_source.rs
src/availability/query_data.rs
src/data_source.rs
src/data_source/extension.rs
src/data_source/fetching.rs
src/data_source/fetching/block.rs
src/data_source/fetching/header.rs
src/data_source/fetching/transaction.rs
src/data_source/fetching/vid.rs
src/data_source/storage.rs
src/data_source/storage/fs.rs
src/data_source/storage/no_storage.rs
src/data_source/storage/sql.rs
src/fetching/provider/query_service.rs
src/lib.rs

Add transaction index within block back to transaction response

---

src/data_source/fetching.rs

* Add a `major_scan_offset` parameter to make it easy to configure a group of nodes so that they all do their major scans at different times
* Log major scans at WARN level so we see it in deployments
* Add a tracing instrument to scans with relevant information
Motivated by this pattern:
The spikes are exactly every hour on all query nodes and correspond with major scans.

Minor improvements to proactive scanning

---

Cargo.lock
Cargo.toml
examples/simple-server.rs
src/availability.rs
src/availability/query_data.rs
src/data_source.rs
src/data_source/fetching/leaf.rs
src/data_source/fs.rs
src/data_source/sql.rs
src/data_source/storage/sql.rs
src/data_source/update.rs
src/fetching/provider/query_service.rs
src/lib.rs
src/node.rs
src/testing/consensus.rs
src/testing/mocks.rs

Update Hotshot to 0.5.55

---

src/data_source/storage/sql.rs

This fixes a query which was found to be slow in production. The query for block height by state commitment had no limit, requiring a full table scan to find all blocks with a certain state commitment even though we only need one.
Adds a `LIMIT 1` to the query looking up block height by state commitment, allowing it to be solved by an index lookup or a short-circuiting table scan.

Add limit to state commitment query

---

src/data_source/fetching.rs
src/data_source/storage/pruning.rs
src/data_source/storage/sql.rs

- Save pruned height after each batch delete and in same transaction block as batch delete
- adjust default interval to 1.5 hours

Do batch delete and pruned height upsert in one transaction block

---

Cargo.lock
Cargo.toml
src/availability.rs
src/error.rs
src/explorer/errors.rs
src/lib.rs
src/merklized_state.rs
src/node.rs
src/status.rs

[WEEKLY RELEASE] HotShot 0.5.57

---

Cargo.lock
Cargo.toml
src/data_source.rs
src/data_source/sql.rs
src/data_source/storage/sql.rs
src/data_source/storage/sql/client.rs

Automatically reset postgres connection when closed

---

Cargo.lock
Cargo.toml

Hotshot/rc 0.5.63

---

Cargo.lock
Cargo.toml
src/data_source/storage/sql.rs
src/explorer/errors.rs

[WEEKLY RELEASE] HotShot - rc-0.5.66

---

Cargo.lock
Cargo.toml
examples/simple-server.rs
src/testing/consensus.rs

[WEEKLY RELEASE] HotShot - rc-0.5.67

---

Cargo.lock
Cargo.toml
examples/simple-server.rs
src/testing/consensus.rs
src/testing/mocks.rs

hotshot-rc0.5.70

---

Cargo.lock
Cargo.toml
examples/simple-server.rs
src/availability.rs
src/data_source.rs
src/data_source/fs.rs
src/data_source/metrics.rs
src/data_source/sql.rs
src/data_source/storage/sql.rs
src/lib.rs
src/testing/consensus.rs
src/testing/mocks.rs

bump hotshot to 0.5.70
see: https://github.com/EspressoSystems/HotShot/pull/3555

bump hotshot version

---

Cargo.lock
Cargo.toml
src/status.rs

[WEEKLY RELEASE] HotShot 0.5.74

---

src/data_source.rs
src/data_source/storage/fs.rs

The test checks for this bug as well as the earlier fixed bug where dropping a mutable SQL transaction causes the next immutable transaction to block

Revert fs transaction on drop and add regression test

---

Cargo.lock
Cargo.toml
examples/simple-server.rs
src/availability.rs
src/availability/query_data.rs
src/data_source.rs
src/data_source/sql.rs
src/data_source/storage/sql.rs
src/lib.rs
src/testing/consensus.rs
src/testing/mocks.rs

[WEEKLY RELEASE] HotShot - rc-0.5.75

---

src/data_source/fetching.rs

By awaiting the objects we are fetching, we ensure that we do not spawn active fetching tasks at a faster rate than they complete, thus preventing a resource leak.

Slow down active fetching task

---

Cargo.lock
Cargo.toml
examples/simple-server.rs
src/testing/consensus.rs

[WEEKLY RELEASE] HotShot - rc-0.5.79
