EspressoSystems/hotshot-query-service

.github/workflows/build.yml, Cargo.lock, Cargo.toml, flake.lock, src/data_source.rs
Per the new methodology described by @elliedavidson, main will always be the latest stable HotShot release, while the new develop branch will be used for unstable development. Thus, we can point at main and not an (old) stable release tag.
=> Point at HotShot main

README.md
During the documentation browsing, I discovered a link pointing to non-existing resource. This PR fixes the issue.
=> fix: update of outdated link

src/data_source.rs, src/data_source/extension.rs, src/data_source/fs.rs, src/data_source/metrics.rs, src/data_source/sql.rs, src/testing/mocks.rs
This probably should have been two separate PRs, sorry about that. Got a little carried away. If you look at the diff for each commit separately, hopefully it is pretty straightforward.
=> Add a feature to reset the SQL database; streamline and extend the public query API

src/data_source/storage/sql.rs
* Detect silent tokio-postgres errors (🙄) by looking at the number of rows modified
* Retry when a statement fails to execute or have an effect
=> Make Postgres storage more robust

Cargo.toml
Making hotshot-testing as part of dev-dependencies as to get rid of some warnings in `testing/mocks.rs`
=> making hotshot-testing non-optional

Cargo.lock, Cargo.toml
we need this for light client integration: https://github.com/EspressoSystems/HotShot/pull/2439
=> chore: update hotshot to 0.5.7.1

.github/workflows/lint.yml, Cargo.lock, Cargo.toml, examples/simple-server.rs, src/availability.rs, src/availability/fetch.rs, src/data_source.rs, src/data_source/extension.rs, src/data_source/fetching.rs, src/data_source/fs.rs, src/data_source/metrics.rs, src/data_source/sql.rs, src/data_source/storage.rs, src/data_source/storage/no_storage.rs, src/fetching/provider/query_service.rs, src/lib.rs, src/task.rs, src/testing/consensus.rs, src/testing/mocks.rs
Implement `NoStorage` which implements the availability storage interface by returning errors for every query. This lets us really stress test fetching. With a few modifications to the tests and new features we had already planned on implementing, we are able to run the availability tests and have them pass without any persistent storage!
**Test modifications**
* We don't enforce that a query for a non-unique payload or transaction
returns the _first_ matching object, if the object needs to be fetched.
We do guarantee this for objects which are stored locally, but there's
no good way to do it when fetching the object, since the proactive fetcher
may provide a matching object in any order. This is not a property anybody relies on anyways.
* Moved the proposer queries to a separate test …
=> Chaos testing: Implement a query storage that relies purely on peer data

api/node.toml, src/availability/query_data.rs, src/data_source.rs, src/data_source/extension.rs, src/data_source/fetching.rs, src/data_source/storage/fs.rs, src/data_source/storage/ledger_log.rs, src/data_source/storage/no_storage.rs, src/data_source/storage/sql.rs, src/lib.rs, src/node.rs, src/node/data_source.rs, src/node/query_data.rs
This endpoint can be used to determine if the database is fully
synced and, if not, how much data is missing. This is useful for
alerts (@Ancient123) as well as for the block explorer to be able to inform the
user when aggregate queries may be inaccurate due to syncing in
progress (@Ayiga).
The query used to count missing data is not indexed or optimized,
but I believe it can be made efficient in the future:
* The `count(*)` to determine the number of leaves we have can be
slow when the `leaf` table is large, because Postgres uses a full
table scan to count. This could be made more efficient a number of
ways, including:
- Using estimated counts instead of exact counts
- Storing in the database the latest count and using triggers to
update it on inserts/updates
- Inserting placeholder rows …
=> Add `/node/sync-status` endpoint to get information about missing data

api/availability.toml, src/availability.rs, src/availability/query_data.rs, src/data_source/storage/sql.rs, src/data_source/update.rs
For the sake of the Block Explorer, as well as potential future utility we
find ourselves in need of a data structure that can describe aspects of
a Block without transmitting the full contents of a Block.  Currently, we
would like the ability to retrieve a Summary of a Block that indicates the
properties of a Block, as well as a summary of how many transactions
are contained within the Block.  In addition we find ourselves needing
to be able to grab a range of these Block Summaries for Pagination
and comparison purposes.
Add BlockSummaryQueryData type
The BlockSummaryQueryData defines the data layout of the Block
Summary endpoints.
Add From trait for BlockQuerySummaryData from BlockQueryData
Since the BlockQuerySummaryData will eventually be able to be
generated entirely from the …
=> Add Block Summaries Endpoints

Cargo.lock, Cargo.toml
This updates query service to use a tag instead of revision. The tag was pushed to reference the same revision, so nothing should change except for the way we reference the version in our Cargo.toml. Using the `rev` was only intended as a temporary solution to avoid creating a bunch of tags while we making a lot of changes..
=> pin hotshot to tag instead of using rev

.github/workflows/build.yml, .github/workflows/build_windows.yml, .github/workflows/debug_build.yml, .github/workflows/lint.yml, api/node.toml, flake.nix, src/data_source.rs, src/data_source/extension.rs, src/data_source/fetching.rs, src/data_source/storage/fs.rs, src/data_source/storage/ledger_log.rs, src/data_source/storage/no_storage.rs, src/data_source/storage/sql.rs, src/data_source/update.rs, src/lib.rs, src/node.rs, src/node/data_source.rs
We now have endpoints to get the total number of transactions
sequenced and the total size of all data sequenced. This is useful
for the block explorer, internal reporting, and marketing.
I also deleted the `UpdateNodeData` trait because it was a headache
to maintain and didn't really accomplish anything that the
`UpdateAvailabilityData` trait didn't already do. In fact, it just
made it confusing what trait was supposed to do what. It is now
explicitly documented that the node module uses the same underlying
data as the availability module.
Closes #342
=> Add aggregate endpoints

Cargo.lock, Cargo.toml, api/status.toml, src/data_source.rs, src/status.rs, src/status/data_source.rs
addresses: https://github.com/EspressoSystems/hotshot-query-service/issues/411
Changes:
- Added status /time_since_last_decide endpoint to retrieve time since last block commit.
- Updated hotshot crates to version 0.5.15.
=> Status endpoint for elapsed time since last block

Cargo.lock, Cargo.toml, src/availability.rs, src/availability/data_source.rs, src/availability/query_data.rs, src/data_source.rs, src/data_source/fetching/vid.rs, src/data_source/sql.rs, src/data_source/storage/fs.rs, src/data_source/update.rs, src/fetching/provider/query_service.rs, src/fetching/request.rs, src/lib.rs, src/node.rs, src/testing.rs
* Handle views 0 and 1, so we no longer have the edge case where VID data is missing for these views
* Fix tests accordingly
* When fetching VID payload or common data from another query service, verify results against expected commitment
* Use standardized VID constructor from HotShot
Closes #355
=> VID improvements

src/data_source/storage/sql.rs
The `--rm` switch tells docker to cleanup containers on termination. Without this an explicit `remove` is required after `stop` to clean up the container and a `prune` to remove arbitrary volumes left behind. While these are not difficult actions to perform, we are often unaware that we need to do them.
I've also changed `kill` to `stop` because `stop` in the drop fn because `stop` attempts to shutdown the container gracefully.
=> Cleanup docker containers on termination

.cargo/audit.toml, .github/workflows/audit.yml, .github/workflows/build.yml, Cargo.lock, Cargo.toml, examples/simple-server.rs, src/availability.rs, src/data_source/fs.rs, src/data_source/storage/ledger_log.rs, src/data_source/storage/pruning.rs, src/lib.rs, src/node.rs, src/status.rs
More info: https://github.com/rust-lang-deprecated/tempdir/issues/45
This crate is causing cargo-audit to fail due to a dependency on
`remove_dir_all`.
https://rustsec.org/advisories/RUSTSEC-2023-0018
=> Cargo audit fixes, separate CI job

Cargo.lock, Cargo.toml, api/availability.toml, api/node.toml, flake.nix, migrations/V10__init_schema.sql, src/availability.rs, src/availability/query_data.rs, src/data_source.rs, src/data_source/extension.rs, src/data_source/fetching.rs, src/data_source/fetching/block.rs, src/data_source/fetching/leaf.rs, src/data_source/fetching/vid.rs, src/data_source/storage/fs.rs, src/data_source/storage/no_storage.rs, src/data_source/storage/sql.rs, src/fetching/provider/any.rs, src/fetching/provider/query_service.rs, src/lib.rs, src/node.rs, src/node/data_source.rs, src/node/query_data.rs, src/testing/mocks.rs, src/types.rs
Now that we have access to the header timestamp in the query service (needed for pruning) we can implement timestamp queries, moving this functionality from extensions in the sequencer into the core query service.
Conversely, since the proposer address has been moved into the block header and integrated with the Espresso fee system, it no longer makes sense to have proposer endpoints in the core query service. These can be implemented as extensions that rely on the specific structure of the sequencer header, if they are needed at all.
=> Implement timestamp queries; drop proposer queries

examples/simple-server.rs, src/availability.rs, src/data_source/fs.rs, src/data_source/storage/ledger_log.rs, src/data_source/storage/no_storage.rs, src/data_source/storage/sql.rs, src/fetching/provider/any.rs, src/fetching/provider/query_service.rs, src/lib.rs, src/node.rs, src/status.rs, src/task.rs, src/testing/consensus.rs
* Switch temp storage from tempdir (deprecated) to tempfile
* Ensure all async tasks get shut down
* Yield periodically in update task to make cancellation more responsive
Depends on #457 
Closes #346
=> Clean up shutdown

Cargo.lock, Cargo.toml, src/data_source/storage/sql.rs
Header data is serialized as serde_json::Value when inserting it into the header table
=> Fix: merkle tree commitment parsing

.github/workflows/build.yml
Moves clippy/rustfmt after build/test.
Ideally these should be separated off, but this is just a quick fix.
=> Move clippy/rustfmt after build/test

src/data_source/storage/sql.rs
Closes #593
The histogram data for the `get_explorer_summary` endpoint of the `Explorer API` is providing its data in the wrong order.  The data is meant to be delivered in `block height` ascending order.  Instead it's being delivered in `block height` descending order.  This pull request changes the sort order of the data being retrieved in the query itself, which corrects the issue.
Make any other significant changes to the logic.
=> Fix explorer summary histogram data order

src/data_source/storage/sql.rs
Currently `TmpDb::init()` attempts to wait for postgres to become ready,
but the logic will panic if `psql` is not available on the
host. But, we should not have any expectation that `psql` be available
on the host. This PR updates the wait loop to run a query w/ `psql` inside
the docker container.
NOTE due to incoming hotshot and sequencer changes this hasn't been properly tested so there
may be some bugs. Once hotshot is updated we can test this properly.
=> Fix: TmpDb::init() wait for psql

src/data_source/storage/sql.rs
We have several queries that filter by timestamp inequality and order by height. These queries have been observed to be extremely slow in practice, because the query planner uses the height index for the ORDER BY clause, and ends up doing a full scan to find the appropriate timestamp range.
Orders such queries by timestamp, then height. This is logically equivalent, since timestamps are monotonic, but it allows the query planner to choose the timestamp index since it solves by the WHERE clause and ORDER BY clause. All that remains is a small incremental sort on height in case there are multiple blocks with the same timestamp. There are never more than a handful such blocks, so this sort is efficient.
=> Optimize queries by timestamp

src/availability.rs, src/data_source.rs, src/data_source/extension.rs, src/data_source/fetching.rs, src/data_source/storage/fs.rs, src/data_source/storage/no_storage.rs, src/data_source/storage/sql.rs, src/lib.rs, src/node.rs, src/node/data_source.rs, src/testing/consensus.rs
This change should reduce the frequency/severity of slow requests due to long queues forming on the lock protecting the API state.
* Uses `at` instead of `get` to manually control locking in request handlers. The changes are focused on requests which might be slow and which don't actually need a lock on the state for their whole duration
* Upgrades all endpoints in the availability API which have a timeout on a `Fetch` so that they don't have a lock while waiting for the timeout
* Refactors the `sync-status` endpoint to make a clone of the SQL client, and run the actual query without borrowing/locking the API state. This allows the (potentially very slow) query to proceed asynchronously from other requests and state updates
=> Fine tune locking to minimize critical sections

src/data_source/fetching.rs, src/data_source/storage/sql.rs
- removes manual vacuum as postgres  runs autovacuum daemon by default and vaccumming can be resource intensive
- sleep after each pruner run
=> Remove manual Vacuum from pruning

src/data_source/storage/sql.rs
Because we were only checking for database readiness from inside the container, there was a case where we would consider the TmpDb "ready" and allow connections before the Docker daemon had actually exposed the database port to the host. This change explicitly checks that the port is exposed on the host before returning, with no extra dependencies on the host side.
This fixes an intermittent "Connection Refused" error that @rob-maron and I were seeing while debugging an unrelated sequencer test failure.
=> Improve reliability of TmpDb startup

src/data_source/storage/sql/transaction.rs, src/lib.rs, src/task.rs
The old method of queuing dropped transactions for revert and then actually doing the revert the next time the transaction is used in an async context can leave idle transactions unreverted for a long time. This may seem ok if the connection is not otherwise being used. However, this can cause `SERIALIZABLE READ ONLY DEFERRABLE` transactions to block indefinitely waiting to acquire a snapshot, since the database sees that there is a writable transaction in progress indefinitely.
The new method ensures transactions are always reverted soon after they are dropped by running the revert in a background task. If the connection is acquired again before the revert has completed, it will block on the cmpletion of the background task, to ensure the connection is not used while the old transaction …
=> Ensure dropped transactions are reverted in a timely manner

src/data_source/storage/sql/query/explorer.rs, src/explorer/query_data.rs
Closes #703
Updates the `ExplorerHistogram` fields for both `time` and `size` to have `Option` values, which can result in a `null` value coming down to the client.
=> Add Option values to Explorer histogram data

src/data_source/storage/sql/query/state.rs
This query was observed to be slow (~3s) in Decaf for one DA node. Not 100% sure this is why, but it might be and should be a harmless change
=> Add LIMIT 1 to query

src/data_source/extension.rs, src/data_source/fetching.rs, src/data_source/metrics.rs, src/data_source/storage/fs.rs, src/data_source/storage/no_storage.rs, src/data_source/storage/sql.rs, src/data_source/storage/sql/transaction.rs, src/lib.rs, src/status/data_source.rs
If the sqlx changes don't fix the issues we're seeing in devnet, this should help with debugging.
Adds the following metrics:
* `sql_open_transactions`: number of transactions currently open
* `transaction_duration`: histogram of transaction durations
* `committed_transactions`: count of transactions closed by committing
* `reverted_transactions`: count of transactions closed by reverting
* `dropped_transactions`: count of transactions closed by dropping (implicit revert)
Adds trace-level logging for transaction lifecycle
=> Add metrics and tracing logging around SQL transactions

Cargo.lock, Cargo.toml, migrations/V100__drop_leaf_payload.sql, src/availability/query_data.rs, src/data_source/fetching.rs, src/data_source/sql.rs, src/data_source/storage/sql.rs, src/fetching/provider/query_service.rs
* Fixes a bug where we might store a leaf with the full block payload, which is redundant because the payload is already stored separately
* Adds a migration to remove payloads from existing leaves
* Changes the spacing between default migrations from 10 to 100 to allow more room for intermediate migrations in the sequencer repo, since we already have 10 migrations there since the last query service migration
=> Do not store payloads with leaves

src/data_source/update.rs
Previously, we panicked if we got an invalid decide event (leaves not chained properly). Now, we return an error. Even if we expect this to never happen, it is easier to monitor and debug if we return an error instead of panicking.
=> Don't panic in update

api/explorer.toml, src/data_source/extension.rs, src/data_source/fetching.rs, src/data_source/fetching/notify_storage.rs, src/data_source/storage.rs, src/data_source/storage/sql/queries/explorer.rs, src/explorer.rs, src/explorer/data_source.rs
addresses https://github.com/EspressoSystems/espresso-block-explorer/issues/148
This PR:
- replaces the prefix search with equality for block and transaction searches
- replace search query parameter type from `String` to `TaggedBase64`
- queries database for blocks or transactions based on the tag
=> Replace explorer prefix search with exact match for block and transaction hash

src/data_source/storage/sql/queries/explorer.rs
addresses https://github.com/EspressoSystems/hotshot-query-service/issues/721
The PR fixes the order by clause for transaction detail query. 
using ORDER BY DESC with an offset caused skipping of recent transactions, resulting in (N - offset)th transaction. This PR changes DESC to ASC  so that older transactions are correctly skipped
=> fix order by clause in getTransactionDetail query

src/data_source/extension.rs, src/data_source/fs.rs, src/data_source/sql.rs, src/data_source/storage/no_storage.rs, src/data_source/update.rs, src/lib.rs
A recent commit made `update` infallible, reasoning that if we fail to store a new leaf, it is better to at least try storing the next one, rather than failing completely. However, this is not accurate: the client uses the success/failure of `udpate` to determine when it is safe to garbage collect data from temporary storage. Thus, returning success when we didn't actually store all the leaves can lead to data loss.
This change fixes the situation by again returning an error whenever we fail to insert a leaf. It also tries to make the return value more useful, by returning on error the height of the first leaf we failed to insert (which is useful for garbage collection) instead of just an opaque error message which the caller can't do much with.
=> Make `update` fallible again

.github/workflows/build.yml, .github/workflows/lint.yml, src/data_source/update.rs
In the sequencer repo we don't have a proper `Default` impl but one that's gated behind the testing feature because it wouldn't actually work.
Working on
https://github.com/EspressoSystems/espresso-sequencer/pull/2283 it seems that this is one of the pain points for removing the spread of the testing features in the sequencer crates.
It looks like we don't need the trait bound anymore in the query service.
=> Remove unused Default bound on InstanceState

src/data_source/storage/sql/queries/availability.rs, src/data_source/storage/sql/queries/explorer.rs
Postgres treats `ORDER BY (col1, col2) [DESC]` _very_ differently from `ORDER BY col1 [DESC], col2 [DESC]`. If there is a multi-column index on `(col1, col2)`, only the latter (without parentheses) will use the index. This is causing some extremely slow queries on Decaf and Mainnet, particularly in the block explorer; these are queries which should be almost trivial.
This may overlap a bit with work done in #728 , however this PR is specifically meant to address this issue exhaustively, and to be standalone, so hopefully we can merge this very quickly, as it's a huge performance improvement.
This changes fixes every occurence of these type of queries.
=> Fix multi-column ORDER BY clauses

.github/workflows/build.yml, api/node.toml, migrations/V200__create_aggregates_table.sql, src/data_source.rs, src/data_source/extension.rs, src/data_source/fetching.rs, src/data_source/fs.rs, src/data_source/sql.rs, src/data_source/storage.rs, src/data_source/storage/fail_storage.rs, src/data_source/storage/fs.rs, src/data_source/storage/no_storage.rs, src/data_source/storage/sql.rs, src/data_source/storage/sql/queries/explorer.rs, src/data_source/storage/sql/queries/node.rs, src/fetching/provider/query_service.rs, src/lib.rs, src/node.rs, src/node/data_source.rs
We have some statistics that are derived from the entire block history, namely transaction count and payload size. Previously, these were computed on the fly each request, which requires an expensive full table scan and, in the case of payload size, a large sum. We saw this causing performance problems on decaf and mainnet, particularly the block explorer, which uses these statistics heavily
Adds a new table `aggregate`, which stores these cumulative values _at each block height_. This table is kept up to date by a background task scanning the block stream. Now, looking up the values of these statistics just requires reading a single row in this table. This approach has numerous benefits in addition to a massive performance improvement:
* we can now easily look up the values of these …
=> Improve efficiency of aggregated statistics

src/data_source/fetching.rs, src/data_source/fetching/block.rs, src/data_source/fetching/header.rs, src/data_source/fetching/leaf.rs, src/data_source/fetching/transaction.rs, src/data_source/fetching/vid.rs, src/data_source/storage/fail_storage.rs, src/data_source/storage/no_storage.rs, src/fetching.rs, src/fetching/provider/query_service.rs
We have observed on Mainnet that when the database is having errors (such as performance issues leading to timeouts acquiring a connection), some fetches never return, because we erroneously believe an object is missing and wait for, when really it was just temporarily inaccessible and no one is fetching it.
* Makes low-level fetching-related functions fallible, so we can more easily distinguish between an object being missing vs temporarily inaccessilbe
* Retries fetch initialization until we successfully trigger the fetch
The guarantee that this change upholds is that every fetch will eventually resolve as long as the requested object is either fetchable or exists in the database already.
See commit messages, comments and new tests for additional details.
=> Improve robustness of fetches during database instability

.config/nextest.toml, migrations/V300__transactions_count.sql, src/availability/data_source.rs, src/availability/query_data.rs, src/data_source.rs, src/data_source/extension.rs, src/data_source/fetching.rs, src/data_source/fetching/block.rs, src/data_source/fetching/vid.rs, src/data_source/storage.rs, src/data_source/storage/fail_storage.rs, src/data_source/storage/fs.rs, src/data_source/storage/no_storage.rs, src/data_source/storage/sql/queries.rs, src/data_source/storage/sql/queries/availability.rs, src/data_source/storage/sql/queries/explorer.rs, src/data_source/storage/sql/queries/node.rs, src/data_source/storage/sql/transaction.rs, src/fetching/provider/query_service.rs, src/lib.rs
Both the scanner and aggregator tasks wait for full blocks to be available, but neither of them actually need the full block data. The aggregator only needs a summary, and the scanner only needs to know that the block exists. It is quite wasteful to load the whole payload or VID common, which might be quite large, especially in the scanner where we really don't care about data we already have.
* Adds new types `PayloadMetadata` and `VidCommonMetadata`, which are like their friends `PayloadQueryData` and `VidCommonQueryData`, but without the large data blobs
* Implement fetching traits for these types which do not load the large data blob when the type is available in the local DB, but _do_ trigger a fetch of the whole object when it is missing from the local DB
* Add a column …
=> Avoid unnecessary loading of full payloads and VID common

src/data_source/fetching.rs, src/data_source/storage.rs, src/data_source/storage/fail_storage.rs, src/data_source/storage/fs.rs, src/data_source/storage/no_storage.rs, src/data_source/storage/sql.rs, src/data_source/storage/sql/queries/node.rs, src/fetching/provider/query_service.rs
I am seeing a lot of database locking errors for sqlite during the update of aggregates. I tried separating the read transaction for the aggregate count from the write transaction, and the locking errors are gone. However, I am not sure why this is happening.
=> separate transactions when updating aggregates

Cargo.lock, Cargo.toml, src/data_source/storage/sql/queries/explorer.rs, src/explorer/query_data.rs, src/explorer/traits.rs, src/testing/mocks.rs
Adjusts some error handling to have the intended error encoding representation.
Adjust the way Explorer queries are handled.  Due to the reference of a local variable within the query strings, they are unable to be static.  The usage of a lazy static library allows for the query strings to be statically set.  They were being constructed in a manner that may have allowed for dependency injection if care was not taken.  They are now set separately, and their lifetimes are external to the queries themselves, allowing for more consistent query handling.
Adjusts the histogram data fetched, so that we don't miss a histogram data point due to missing the prior data point in the results.
=> Adjust Explorer Query and Error Handling
